# Generated by Django 4.0 on 2021-12-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='models1',
            new_name='Todo',
        ),
    ]
